'use client';

import { useEffect, useState, useCallback, useMemo } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import ReportCard from '@/components/ReportCard';
import PriceGauge from '@/components/PriceGauge';
import { ArrowLeft, Download, AlertCircle, CheckCircle, Loader2, Filter, ArrowDown } from 'lucide-react';
import Link from 'next/link';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface LineItemAnalysis {
  item_name: string;
  quoted_price: number;
  fair_price_low: number;
  fair_price_high: number;
  assessment: 'fair' | 'slightly_high' | 'high' | 'gouging' | 'suspiciously_low' | 'unknown';
  explanation: string;
  bls_rate?: number;
  material_cost?: number;
}

interface TypicalCostItem {
  item_name: string;
  typical_low: number;
  typical_high: number;
  description: string;
}

interface Report {
  id: string;
  project_type: string;
  location: string;
  total_quoted: number;
  total_fair_low: number;
  total_fair_high: number;
  overall_assessment: string;
  line_items: LineItemAnalysis[];
  created_at: string;
  // Total-only quote estimation fields
  is_estimated?: boolean;
  estimation_confidence?: string;
  estimation_methodology?: string;
  typical_costs?: TypicalCostItem[];
}

type FilterType = 'all' | 'issues' | 'gouging' | 'high' | 'fair' | 'suspiciously_low';

const ASSESSMENT_ORDER: Record<string, number> = {
  gouging: 0,
  high: 1,
  slightly_high: 2,
  suspiciously_low: 3,
  unknown: 4,
  fair: 5,
};

export default function ReportPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const reportId = params.id as string;
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pdfDownloading, setPdfDownloading] = useState(false);
  const [showPaymentSuccess, setShowPaymentSuccess] = useState(false);
  const [activeFilter, setActiveFilter] = useState<FilterType>('all');
  const [sortByIssues, setSortByIssues] = useState(false);

  // Payment success banner
  useEffect(() => {
    if (searchParams.get('payment') === 'success') {
      setShowPaymentSuccess(true);
      const timer = setTimeout(() => setShowPaymentSuccess(false), 5000);
      return () => clearTimeout(timer);
    }
  }, [searchParams]);

  // PDF download handler — uses server-side ReportLab PDF (branded, professional)
  const handleDownloadPdf = useCallback(async () => {
    if (pdfDownloading) return;
    setPdfDownloading(true);

    try {
      // Primary: server-side ReportLab PDF (branded header, estimation disclaimers, no DOM issues)
      const response = await fetch(`/api/quotes/${reportId}/pdf`, {
        credentials: 'include',
      });
      if (!response.ok) throw new Error(`Server PDF failed: ${response.status}`);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `ungouge-report-${reportId}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err: unknown) {
      console.error('Server PDF failed, falling back to client-side capture:', err);
      // Fallback: html2canvas DOM capture
      try {
        const reportEl = document.getElementById('report-content');
        if (!reportEl) throw new Error('Report element not found');

        const prevFilter = activeFilter;
        const prevSort = sortByIssues;
        setActiveFilter('all');
        setSortByIssues(false);
        await new Promise(r => setTimeout(r, 300));

        const canvas = await html2canvas(reportEl, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: '#F9FAFB',
          windowWidth: 1200,
        });

        const imgData = canvas.toDataURL('image/jpeg', 0.95);
        const imgWidth = 210;
        const pageHeight = 297;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        const pdf = new jsPDF('p', 'mm', 'a4');
        let heightLeft = imgHeight;
        let position = 0;

        pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;

        while (heightLeft > 0) {
          position -= pageHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
          heightLeft -= pageHeight;
        }

        const totalPages = pdf.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(8);
          pdf.setTextColor(156, 163, 175);
          pdf.text(
            `Generated by GougeAlert — Page ${i} of ${totalPages}`,
            105, 290, { align: 'center' }
          );
        }

        pdf.save(`ungouge-report-${reportId}.pdf`);
        setActiveFilter(prevFilter);
        setSortByIssues(prevSort);
      } catch {
        alert('Failed to download PDF. Please try again.');
      }
    } finally {
      setPdfDownloading(false);
    }
  }, [reportId, pdfDownloading, activeFilter, sortByIssues]);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const response = await fetch(`/api/quotes/${reportId}`, {
          credentials: 'include',
        });

        if (!response.ok) {
          if (response.status === 401) {
            setError('Please log in to view this report.');
          } else if (response.status === 403) {
            setError('You do not have permission to view this report.');
          } else if (response.status === 404) {
            setError('Report not found. Please check your report ID.');
          } else {
            setError('Failed to load report. Please try again later.');
          }
          return;
        }

        const data = await response.json();
        setReport(data);
      } catch (err: unknown) {
        if (err instanceof Error) {
          setError(err.message);
        } else {
          setError('Failed to load report. Please check your connection.');
        }
        console.error('Report fetch error:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [reportId]);

  // Compute issue counts for filter badges
  const issueCounts = useMemo(() => {
    if (!report) return { gouging: 0, high: 0, slightly_high: 0, fair: 0, suspiciously_low: 0, issues: 0 };
    const counts = { gouging: 0, high: 0, slightly_high: 0, fair: 0, suspiciously_low: 0, unknown: 0, issues: 0 };
    for (const item of report.line_items) {
      const a = item.assessment;
      if (a in counts) counts[a as keyof typeof counts]++;
      if (a === 'gouging' || a === 'high' || a === 'slightly_high') counts.issues++;
    }
    return counts;
  }, [report]);

  // Filtered + sorted line items
  const filteredItems = useMemo(() => {
    if (!report) return [];
    let items = [...report.line_items];

    // Filter
    if (activeFilter === 'issues') {
      items = items.filter(i => ['gouging', 'high', 'slightly_high'].includes(i.assessment));
    } else if (activeFilter === 'gouging') {
      items = items.filter(i => i.assessment === 'gouging');
    } else if (activeFilter === 'high') {
      items = items.filter(i => ['high', 'slightly_high'].includes(i.assessment));
    } else if (activeFilter === 'fair') {
      items = items.filter(i => i.assessment === 'fair');
    } else if (activeFilter === 'suspiciously_low') {
      items = items.filter(i => i.assessment === 'suspiciously_low');
    }

    // Sort: worst issues first
    if (sortByIssues || activeFilter !== 'all') {
      items.sort((a, b) => {
        const aOrder = ASSESSMENT_ORDER[a.assessment] ?? 4;
        const bOrder = ASSESSMENT_ORDER[b.assessment] ?? 4;
        if (aOrder !== bOrder) return aOrder - bOrder;
        // Secondary: highest overpayment first
        const aOver = a.quoted_price - a.fair_price_high;
        const bOver = b.quoted_price - b.fair_price_high;
        return bOver - aOver;
      });
    }

    return items;
  }, [report, activeFilter, sortByIssues]);

  // Format overall assessment into structured sections
  const formatAssessment = (text: string) => {
    if (!text) return null;

    // Clean up spacing artifacts from AI (e.g., "$204, 3 0 0" → "$204,300")
    let cleaned = text.replace(/(\$[\d,]+),?\s+(\d)\s+(\d)\s+(\d)/g, (_, prefix, a, b, c) => `${prefix}${a}${b}${c}`);
    cleaned = cleaned.replace(/(\$[\d,]+)\s+(\d{3})/g, '$1$2');

    // Detect if the text has markdown structure
    const hasMarkdown = /^#{2,3}\s|\*\*[A-Z]/m.test(cleaned);

    if (hasMarkdown) {
      // Split by markdown headers or bold titles
      const sections = cleaned.split(/(?=##\s)|(?=###\s)|(?=\*\*[A-Z])/g).filter(s => s.trim());
      return sections.map((section, i) => renderSection(section.trim(), i));
    }

    // Plain text: split into sentences and group into logical paragraphs
    // Look for numbered items like "1) " or "1. " or "1 " (just digit + space before capital)
    const numberedPattern = /(?:^|\n)\s*\d+[\.\)]\s|(?:^|\.\s+)\d+\s+[A-Z]/;
    const hasNumberedList = numberedPattern.test(cleaned);

    if (hasNumberedList) {
      // Split on numbered items (handles "1) ", "1. ", and "1 Direct..." patterns)
      const parts = cleaned.split(/(?=\d+[\.\)]\s)|(?<=\.\s)(?=\d+\s+[A-Z])/g).filter(s => s.trim());
      const intro = parts[0]?.match(/^\d/) ? null : parts.shift();
      return (
        <>
          {intro && <p className="mb-4 text-gray-700 leading-relaxed">{intro.trim()}</p>}
          <div className="space-y-3">
            {parts.map((part, i) => {
              const cleaned = part.trim();
              // Extract the number prefix and content
              const match = cleaned.match(/^(\d+[\.\):]?)\s*(.*)/s);
              if (match) {
                return (
                  <div key={i} className="flex gap-3 p-3 bg-gray-50 rounded-lg">
                    <span className="flex-shrink-0 w-7 h-7 bg-primary-100 text-primary-700 rounded-full flex items-center justify-center text-sm font-bold">
                      {match[1].replace(/[\.\)]/, '')}
                    </span>
                    <p className="text-gray-700 leading-relaxed flex-1">{match[2].trim()}</p>
                  </div>
                );
              }
              return <p key={i} className="mb-3 text-gray-700 leading-relaxed">{cleaned}</p>;
            })}
          </div>
        </>
      );
    }

    // Plain text without structure: split into sentences, group ~2-3 sentences per paragraph
    const sentences = cleaned.match(/[^.!?]+[.!?]+/g) || [cleaned];
    const paragraphs: string[] = [];
    let current = '';
    for (const sentence of sentences) {
      current += sentence;
      // Break after 2-3 sentences or at natural topic shifts
      const sentenceCount = (current.match(/[.!?]+/g) || []).length;
      if (sentenceCount >= 2 && current.length > 150) {
        paragraphs.push(current.trim());
        current = '';
      }
    }
    if (current.trim()) paragraphs.push(current.trim());

    // Find key phrases to highlight
    return paragraphs.map((para, i) => {
      // Check for red flag / recommendation keywords
      const isRedFlag = /red flag|goug|overpriced|significantly|warning|concern|caution/i.test(para);
      const isRecommendation = /recommend|should|suggest|advise|obtain|consider|negotiate/i.test(para);
      const isPositive = /fair|reasonable|competitive|well-priced|good value/i.test(para) && !isRedFlag;

      if (isRedFlag) {
        return (
          <div key={i} className="mb-3 p-4 bg-red-50 border-l-4 border-red-400 rounded-r-lg">
            <p className="text-gray-800 leading-relaxed">
              <span className="font-semibold text-red-700">🚩 </span>
              {para}
            </p>
          </div>
        );
      }
      if (isRecommendation) {
        return (
          <div key={i} className="mb-3 p-4 bg-blue-50 border-l-4 border-blue-400 rounded-r-lg">
            <p className="text-gray-800 leading-relaxed">
              <span className="font-semibold text-blue-700">💡 </span>
              {para}
            </p>
          </div>
        );
      }
      if (isPositive && i === 0) {
        return (
          <div key={i} className="mb-3 p-4 bg-emerald-50 border-l-4 border-emerald-400 rounded-r-lg">
            <p className="text-gray-800 leading-relaxed">
              <span className="font-semibold text-emerald-700">✅ </span>
              {para}
            </p>
          </div>
        );
      }
      return <p key={i} className="mb-3 text-gray-700 leading-relaxed">{para}</p>;
    });
  };

  const renderSection = (trimmed: string, i: number) => {
    // Check if it's a header line
    const headerMatch = trimmed.match(/^(#{2,3})\s+(.+)/);
    if (headerMatch) {
      const level = headerMatch[1].length;
      const title = headerMatch[2];
      const body = trimmed.replace(/^#{2,3}\s+.+\n?/, '').trim();
      return (
        <div key={i} className="mb-4">
          {level === 2 ? (
            <h3 className="text-lg font-bold text-gray-900 mb-2">{title}</h3>
          ) : (
            <h4 className="text-base font-semibold text-gray-800 mb-1">{title}</h4>
          )}
          {body && <div className="text-gray-700 leading-relaxed whitespace-pre-line">{body}</div>}
        </div>
      );
    }

    // Check for bold title lines like **Summary:**
    const boldMatch = trimmed.match(/^\*\*(.+?)\*\*[:\s]*([\s\S]*)/);
    if (boldMatch) {
      return (
        <div key={i} className="mb-4">
          <h4 className="text-base font-semibold text-gray-800 mb-1">{boldMatch[1]}</h4>
          {boldMatch[2] && <div className="text-gray-700 leading-relaxed whitespace-pre-line">{boldMatch[2].trim()}</div>}
        </div>
      );
    }

    // Bullet points
    if (trimmed.includes('\n•') || trimmed.includes('\n-') || trimmed.startsWith('•') || trimmed.startsWith('-')) {
      const lines = trimmed.split('\n');
      return (
        <ul key={i} className="mb-4 space-y-1.5">
          {lines.map((line, j) => {
            const cleaned = line.replace(/^[\s•\-*]+/, '').trim();
            if (!cleaned) return null;
            return (
              <li key={j} className="flex items-start gap-2 text-gray-700">
                <span className="text-primary-500 mt-1.5 flex-shrink-0">•</span>
                <span className="leading-relaxed">{cleaned}</span>
              </li>
            );
          })}
        </ul>
      );
    }

    // Regular paragraph
    return <p key={i} className="mb-3 text-gray-700 leading-relaxed">{trimmed}</p>;
  };

  if (loading) {
    return (
      <div className="py-20 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading your report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="py-20">
        <div className="container mx-auto px-4 max-w-2xl">
          <div className="card text-center">
            <AlertCircle className="w-16 h-16 text-danger mx-auto mb-4" />
            <h1 className="text-2xl font-bold mb-4">Report Not Found</h1>
            <p className="text-gray-600 mb-6">{error || 'The report you\'re looking for doesn\'t exist.'}</p>
            <Link href="/analyze" className="btn-primary">
              Analyze a New Quote
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // Calculate savings potential
  const totalOverpay = report.total_quoted - report.total_fair_high;
  let savingsPotential: number;

  if (report.is_estimated) {
    // Total-only quotes: use total-level comparison only
    savingsPotential = totalOverpay > 0 ? totalOverpay : 0;
  } else {
    // Itemized quotes: sum individual line item overpayments
    const itemSavings = report.line_items.reduce((sum, item) => {
      const over = item.quoted_price - item.fair_price_high;
      return sum + (over > 0 ? over : 0);
    }, 0);
    savingsPotential = Math.max(itemSavings, totalOverpay > 0 ? totalOverpay : 0);
  }

  return (
    <div className="py-12 bg-gray-50">
      <div className="container mx-auto px-4 max-w-6xl">
        <Link href="/" className="inline-flex items-center text-primary-600 hover:text-primary-700 mb-6">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>

        {/* Capturable report content for PDF export */}
        <div id="report-content">

        {/* Payment Success Banner */}
        {showPaymentSuccess && (
          <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg flex items-center gap-3 animate-in fade-in duration-300">
            <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" />
            <p className="text-green-800 font-medium">Payment confirmed! Your report is ready.</p>
          </div>
        )}

        {/* Total-Only Quote Notice */}
        {report.is_estimated && (
          <div className="card border-l-4 border-amber-400 bg-amber-50 mb-6">
            <div className="flex items-start gap-4">
              <AlertCircle className="w-8 h-8 text-amber-600 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-bold text-amber-900 mb-2">
                  📋 Total-Only Quote Analysis
                </h3>
                <p className="text-amber-800 mb-3">
                  Your contractor provided only a total price with no per-item breakdown.
                  We&apos;ve analyzed the <strong>total price</strong> against current market data for
                  your area and provided typical cost ranges for each work item as educational guidance.
                </p>
                <div className="bg-amber-100 border border-amber-300 rounded-lg p-3">
                  <p className="text-amber-900 text-sm font-semibold">
                    💡 Want detailed per-item analysis?
                  </p>
                  <p className="text-amber-800 text-xs mt-1">
                    Ask your contractor for an itemized breakdown and re-submit it.
                    Itemized quotes give you much stronger negotiating power.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Header */}
        <div className="card mb-8">
          <div className="flex justify-between items-start mb-6">
            <div>
              <h1 className="text-3xl font-bold mb-2">Quote Analysis Report</h1>
              <p className="text-gray-600">
                {report.project_type} • {report.location}
              </p>
              <p className="text-sm text-gray-500 mt-1">
                Generated: {new Date(report.created_at).toLocaleDateString()}
              </p>
            </div>
            <button
              onClick={handleDownloadPdf}
              disabled={pdfDownloading}
              className="btn-secondary flex items-center disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {pdfDownloading ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Download className="w-4 h-4 mr-2" />
              )}
              {pdfDownloading ? 'Generating...' : 'Download PDF'}
            </button>
          </div>

          {/* Overall Summary — numbers */}
          <div className="grid md:grid-cols-3 gap-6 mb-6">
            <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
              <p className="text-sm text-gray-500 mb-1 uppercase tracking-wide font-medium">Total Quoted</p>
              <p className="text-3xl font-bold text-gray-900">${report.total_quoted.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
            </div>
            <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-5 shadow-sm">
              <p className="text-sm text-emerald-700 mb-1 uppercase tracking-wide font-medium">Fair Price Range</p>
              <p className="text-3xl font-bold text-emerald-700">
                ${report.total_fair_low.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} – ${report.total_fair_high.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </p>
            </div>
            <div className={`rounded-xl p-5 shadow-sm border ${savingsPotential > 0 ? 'bg-amber-50 border-amber-200' : 'bg-emerald-50 border-emerald-200'}`}>
              <p className={`text-sm mb-1 uppercase tracking-wide font-medium ${savingsPotential > 0 ? 'text-amber-700' : 'text-emerald-700'}`}>
                {savingsPotential > 0 ? 'Negotiation Savings' : 'Savings Potential'}
              </p>
              <p className={`text-3xl font-bold ${savingsPotential > 0 ? 'text-amber-700' : 'text-emerald-700'}`}>
                {savingsPotential > 0 ? `$${savingsPotential.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : 'None found'}
              </p>
              {savingsPotential > 0 && (
                <p className="text-xs text-amber-600 mt-1">
                  {report.is_estimated
                    ? 'Based on total vs fair market range'
                    : `Based on ${report.line_items.filter(i => i.quoted_price > i.fair_price_high).length} item${report.line_items.filter(i => i.quoted_price > i.fair_price_high).length > 1 ? 's' : ''} above fair range`
                  }
                </p>
              )}
            </div>
          </div>

          {/* Issue Quick-Jump Pills (itemized quotes only) */}
          {!report.is_estimated && issueCounts.issues > 0 && (
            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-xl">
              <div className="flex flex-wrap items-center gap-3">
                <span className="text-sm font-bold text-red-800">
                  ⚠️ {issueCounts.issues} item{issueCounts.issues > 1 ? 's' : ''} need attention:
                </span>
                {issueCounts.gouging > 0 && (
                  <button
                    onClick={() => { setActiveFilter('gouging'); setSortByIssues(true); document.getElementById('line-items')?.scrollIntoView({ behavior: 'smooth' }); }}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-red-600 text-white text-sm font-semibold rounded-full hover:bg-red-700 transition-colors shadow-sm"
                  >
                    🚨 {issueCounts.gouging} Possible Gouge{issueCounts.gouging > 1 ? 's' : ''}
                    <ArrowDown className="w-3 h-3" />
                  </button>
                )}
                {issueCounts.high > 0 && (
                  <button
                    onClick={() => { setActiveFilter('high'); setSortByIssues(true); document.getElementById('line-items')?.scrollIntoView({ behavior: 'smooth' }); }}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-orange-500 text-white text-sm font-semibold rounded-full hover:bg-orange-600 transition-colors shadow-sm"
                  >
                    🔶 {issueCounts.high} High
                    <ArrowDown className="w-3 h-3" />
                  </button>
                )}
                {issueCounts.slightly_high > 0 && (
                  <button
                    onClick={() => { setActiveFilter('high'); setSortByIssues(true); document.getElementById('line-items')?.scrollIntoView({ behavior: 'smooth' }); }}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-amber-500 text-white text-sm font-semibold rounded-full hover:bg-amber-600 transition-colors shadow-sm"
                  >
                    ⚠️ {issueCounts.slightly_high} Slightly High
                    <ArrowDown className="w-3 h-3" />
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Overall Gauge */}
          <PriceGauge
            quotedPrice={report.total_quoted}
            fairLow={report.total_fair_low}
            fairHigh={report.total_fair_high}
          />

          {/* Formatted Overall Assessment */}
          <div className="mt-6 bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
            <h3 className="text-xl font-bold text-gray-900 mb-4 pb-3 border-b border-gray-100">
              📋 Overall Assessment
            </h3>
            <div className="prose prose-sm max-w-none">
              {formatAssessment(report.overall_assessment)}
            </div>
          </div>
        </div>

        {/* Typical Costs Section (for total-only quotes) */}
        {report.is_estimated && report.typical_costs && report.typical_costs.length > 0 ? (
          <div id="typical-costs" className="scroll-mt-4">
            <h2 className="text-2xl font-bold mb-2">Typical Costs in Your Area</h2>
            <p className="text-gray-600 mb-6">
              These are typical market ranges for {report.project_type.toLowerCase()} work items
              in <strong>{report.location}</strong>, based on current market data.
              These are general ranges — not what your contractor is charging for each item.
            </p>

            <div className="space-y-4">
              {report.typical_costs.map((item, index) => (
                <div key={`${item.item_name}-${index}`} className="card border border-gray-200 hover:border-primary-200 transition-colors">
                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-gray-900 mb-1">{item.item_name}</h3>
                      <p className="text-gray-600 text-sm leading-relaxed">{item.description}</p>
                    </div>
                    <div className="sm:text-right flex-shrink-0">
                      <p className="text-sm text-gray-500 uppercase tracking-wide font-medium mb-1">Typical Range</p>
                      <p className="text-xl font-bold text-primary-700">
                        ${item.typical_low.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
                        {' – '}
                        ${item.typical_high.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* CTA: Get itemized quote */}
            <div className="mt-8 card bg-primary-50 border border-primary-200 text-center">
              <h3 className="text-lg font-bold text-primary-900 mb-2">
                💡 Want Per-Item Analysis?
              </h3>
              <p className="text-primary-800 mb-4">
                Ask your contractor for an itemized breakdown showing costs for each work item.
                Then re-submit it to GougeAlert for detailed fair-price ratings on every line item —
                giving you real negotiating power.
              </p>
              <Link href="/analyze" className="btn-primary inline-block">
                Analyze an Itemized Quote
              </Link>
            </div>
          </div>
        ) : (
          /* Line Items Section (for itemized quotes) */
          <div id="line-items" className="scroll-mt-4">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
              <h2 className="text-2xl font-bold">Line Item Breakdown</h2>

              {/* Filter Controls */}
              <div className="flex flex-wrap items-center gap-2">
                <Filter className="w-4 h-4 text-gray-500" />
                <button
                  onClick={() => { setActiveFilter('all'); setSortByIssues(false); }}
                  className={`px-3 py-1.5 text-sm font-medium rounded-full transition-colors ${
                    activeFilter === 'all'
                      ? 'bg-gray-900 text-white'
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  }`}
                >
                  All ({report.line_items.length})
                </button>
                {issueCounts.issues > 0 && (
                  <button
                    onClick={() => { setActiveFilter('issues'); setSortByIssues(true); }}
                    className={`px-3 py-1.5 text-sm font-medium rounded-full transition-colors ${
                      activeFilter === 'issues'
                        ? 'bg-red-600 text-white'
                        : 'bg-red-50 text-red-700 hover:bg-red-100'
                    }`}
                  >
                    ⚠️ Issues ({issueCounts.issues})
                  </button>
                )}
                {issueCounts.gouging > 0 && (
                  <button
                    onClick={() => { setActiveFilter('gouging'); setSortByIssues(true); }}
                    className={`px-3 py-1.5 text-sm font-medium rounded-full transition-colors ${
                      activeFilter === 'gouging'
                        ? 'bg-red-600 text-white'
                        : 'bg-red-50 text-red-700 hover:bg-red-100'
                    }`}
                  >
                    🚨 Possible Gouge ({issueCounts.gouging})
                  </button>
                )}
                {issueCounts.fair > 0 && (
                  <button
                    onClick={() => { setActiveFilter('fair'); setSortByIssues(false); }}
                    className={`px-3 py-1.5 text-sm font-medium rounded-full transition-colors ${
                      activeFilter === 'fair'
                        ? 'bg-emerald-600 text-white'
                        : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
                    }`}
                  >
                    ✅ Fair ({issueCounts.fair})
                  </button>
                )}
                {issueCounts.suspiciously_low > 0 && (
                  <button
                    onClick={() => { setActiveFilter('suspiciously_low'); setSortByIssues(false); }}
                    className={`px-3 py-1.5 text-sm font-medium rounded-full transition-colors ${
                      activeFilter === 'suspiciously_low'
                        ? 'bg-blue-600 text-white'
                        : 'bg-blue-50 text-blue-700 hover:bg-blue-100'
                    }`}
                  >
                    ⚡ Suspiciously Low ({issueCounts.suspiciously_low})
                  </button>
                )}
              </div>
            </div>

            {/* Filtered results count */}
            {activeFilter !== 'all' && (
              <p className="text-sm text-gray-500 mb-4">
                Showing {filteredItems.length} of {report.line_items.length} items
                {' '}
                <button onClick={() => { setActiveFilter('all'); setSortByIssues(false); }} className="text-primary-600 hover:underline">
                  Show all
                </button>
              </p>
            )}

            <div className="space-y-6">
              {filteredItems.map((item, index) => (
                <ReportCard key={`${item.item_name}-${index}`} lineItem={item} />
              ))}
            </div>

            {filteredItems.length === 0 && (
              <div className="card text-center py-12">
                <p className="text-gray-500 text-lg">No items match this filter.</p>
                <button onClick={() => { setActiveFilter('all'); setSortByIssues(false); }} className="mt-4 text-primary-600 hover:underline font-medium">
                  Show all items
                </button>
              </div>
            )}
          </div>
        )}

        </div>{/* End report-content */}

        {/* Actions */}
        <div className="mt-12 card text-center">
          <h3 className="text-2xl font-bold mb-4">What&apos;s Next?</h3>
          <p className="text-gray-600 mb-6">
            Use this report to negotiate with your contractor or get additional quotes for comparison.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/analyze" className="btn-primary">
              Analyze Another Quote
            </Link>
            <Link href="/dashboard/quotes" className="btn-secondary">
              My Quotes
            </Link>
            <button onClick={handleDownloadPdf} className="btn-secondary flex items-center justify-center">
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
