import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ChatWidget from '@/components/ChatWidget';
import CookieConsent from '@/components/CookieConsent';
import PlausibleAnalytics from '@/components/PlausibleAnalytics';
import ErrorBoundary from '@/components/ErrorBoundary';
import { AuthProvider } from '@/providers/AuthProvider';
import {
  DEFAULT_METADATA,
  SITE_CONFIG,
  generateOrganizationSchema,
  renderJsonLd,
} from '@/lib/seo';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

// Default metadata for all pages (can be overridden per page)
export const metadata: Metadata = {
  metadataBase: new URL(SITE_CONFIG.url),
  title: {
    default: DEFAULT_METADATA.title,
    template: '%s | UnGouge — Independent Quote Verification',
  },
  description:
    'Is your contractor quote fair? UnGouge.ai analyzes contractor quotes against real Bureau of Labor Statistics labor rates and regional material costs. Independent, data-backed price verification for homeowners — no lead gen, no contractor kickbacks.',
  keywords: [
    'contractor quote verification',
    'home improvement pricing',
    'contractor quote analysis',
    'fair contractor pricing',
    'is my contractor quote fair',
    'contractor overcharge',
    'home renovation cost check',
    'BLS labor data',
    'contractor price comparison',
    'home improvement quote analyzer',
    'independent quote verification',
    'homeowner protection',
    'no lead gen',
    'kitchen remodel cost',
    'bathroom renovation pricing',
    'roofing quote check',
  ],
  authors: [{ name: 'Ungouge.ai Team' }],
  creator: 'Ungouge.ai',
  publisher: 'Ungouge.ai',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_CONFIG.url,
    siteName: SITE_CONFIG.name,
    title: 'Is Your Contractor Quote Fair?',
    description:
      'Upload your quote and find out in 60 seconds. 9,000+ cost data points, 45+ project types, zero lead generation. $19.99 per report.',
  },
  twitter: {
    card: 'summary_large_image',
    site: SITE_CONFIG.twitterHandle,
    creator: SITE_CONFIG.twitterHandle,
    title: 'Is Your Contractor Quote Fair?',
    description:
      'Upload your quote and find out in 60 seconds. No lead gen — we work for homeowners, not contractors.',
  },
  // Images auto-generated by app/opengraph-image.tsx

  alternates: {
    canonical: DEFAULT_METADATA.canonical,
  },
  other: {
    'theme-color': '#2563eb',
  },
  verification: {
    // Add verification codes when available
    // google: 'your-google-verification-code',
    // yandex: 'your-yandex-verification-code',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Organization schema is site-wide; page-specific schemas live in page.tsx files
  const organizationSchema = generateOrganizationSchema();

  return (
    <html lang="en">
      <head>
        {/* Site-wide Organization JSON-LD */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={renderJsonLd(organizationSchema)}
        />
      </head>
      <body className={inter.variable}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <ErrorBoundary>
              <main className="flex-grow">
                <Suspense fallback={
                  <div className="min-h-screen flex items-center justify-center">
                    <div className="text-center">
                      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4" />
                      <p className="text-gray-600">Loading...</p>
                    </div>
                  </div>
                }>
                  {children}
                </Suspense>
              </main>
            </ErrorBoundary>
            <Footer />
            <Suspense fallback={null}>
              <CookieConsent />
            </Suspense>
            <Suspense fallback={null}>
              <ChatWidget />
            </Suspense>
            <Suspense fallback={null}>
              <PlausibleAnalytics />
            </Suspense>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
